language: java

jdk:
 - openjdk12

os:
  - linux

script:
  - cd server
  - mvn package dockerfile:build

branches:
  only:
    - master
    - dgk
    - qwe
    - develop

after_success:
  - bash <(curl -s https://codecov.io/bash)
